version: '3.9'
services:
  ssh1.cyrhades.fr:
    build:
      context: ./.docker/ssh
      args:
        filename: message1.txt
  ssh2.cyrhades.fr:
    build:
      context: ./.docker/ssh
      args:
        filename: message2.txt
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  bugs-buggy-oracle.cyrhades.fr:
    image: anssi/fcsc2020-crypto-bugs-buggy-oracle:latest
    ports:
      - "4000:4000"
  bugs-buggy-python.cyrhades.fr:
    image: anssi/fcsc2020-crypto-bugs-buggy-python:latest
    ports:
      - "4001:4000"
